### ISSUE TITLE
Possible layout change

### ISSUE THREAD

**Issue by heyner29** [enso-ui/forms#17]
This is  a **question for feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

Hello, do you think there is any way to use forms but with a custom design?

I understand that I can use slots to customize the behavior of each field a little as [the documentation](https://docs.laravel-enso.com/frontend/forms.html#slots) indicates, but in my case I would also like to change the layout of the fields something similar to this.
![form](https://user-images.githubusercontent.com/12703614/84584899-7b7f5780-adcf-11ea-882a-c530e9cff0fb.png)

But I am getting this error, which I understand is from vue and not from the component.

![image](https://user-images.githubusercontent.com/12703614/84584844-dbc1c980-adce-11ea-8881-7530b7b60218.png)

I would appreciate your support if at any time you have faced a similar case or perhaps have notions of the subject.

Thank you!

**Comment by aocneanu** [comment]
You can make the whole section custom, by setting it's attributes:

```
"columns": "slot",
"slot": "my-slot",
```

**Comment by heyner29** [comment]
Thank you, this is how my form looks now
![image](https://user-images.githubusercontent.com/12703614/84594687-a8f0f300-ae19-11ea-8843-30fb8bb18475.png)

And so my .vue file
![image](https://user-images.githubusercontent.com/12703614/84594702-c32ad100-ae19-11ea-9b7d-49b547444347.png)
