### ISSUE TITLE
meta.disabled vs meta.hidden different behavior

### ISSUE THREAD

**Issue by robbykrlos** [enso-ui/forms#24]
This is  a **bug**.

I noticed (not sure if intentional or not) that there is a slight difference in how meta.disabled and meta.hidden are behaving:
Ex:

**This works:**
```vue
toggleDisabled: function (disabled) {
            this.$refs.form.field('myField').meta.disabled = !disabled;
            //and by works, I mean that the page reflects the diasabled state, so the rendering is forced.
        },
```

**This doesn't:**
```vue
toggleHidden: function (hidden) {
            this.$refs.form.field('myField').meta.hidden = !hidden;
            //this alone is not working because it needs next line uncommented - it does not force the rendering
            //this.$refs.form.$forceUpdate();
        },
```

I tried searching for a watch on ``disabled`` hoping that maybe a watch on hidden is missing, but didn't find any related to fields - or maybe I didn't dig deep enough...

Any suggestions?

**Comment by raftx24** [comment]
I guess the reason is that you have `disabled` in your meta field but you don't have `hidden`.

**Comment by robbykrlos** [comment]
> I guess the reason is that you have `disabled` in your meta field but you don't have `hidden`.

Hi @raftx24,

You mean in the json file? Like this?

```json
"meta": {
            "custom": false,
            "type": "input",
            "content": "text",
            "disabled": false
          }
```

**Comment by aocneanu** [comment]
yes. If the property is not present here then it's not reactive in the FE

**Comment by robbykrlos** [comment]
Nice, Thanks!
