### ISSUE TITLE
no reactive translation

### ISSUE THREAD

**Issue by YacoubBelaoura** [enso-ui/forms#3]
This is  a **bug ?**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

in Forms when changing one lang to an other the fields will hold the old language, as in the provided screenshots.

![ENgARa](https://user-images.githubusercontent.com/18699402/55401186-e5ec0500-5547-11e9-8826-ab2c63836faa.png)
![EngAR](https://user-images.githubusercontent.com/18699402/55401187-e6849b80-5547-11e9-896d-8af1a908cba3.png)

### Steps to Reproduce
for example 
1. open `Edit Permission` and change language to an other. like from english to arabic 'so the change will be visible' 
2. you will see that the select field still hold the older language
3. you will need to refresh the page

### Expected behavior
the language change on fields to

### Actual behavior
the fields still hold the older language

## reason ?
i think its related to this from vuejs docs.

> Note: the provide and inject bindings are NOT reactive. This is intentional. However, if you pass down an observed object, properties on that object do remain reactive.

and i think the injected 'i18n' is not.

**Comment by aocneanu** [comment]
It's not a bug.

`vue-select` does not (at least for the moment) translate it's options, and what you see there are Enums values that get translated in the backend.

I guess we could add this feature.

**Comment by aocneanu** [comment]
BTW

>Note: the provide and inject bindings are NOT reactive. This is intentional. However, if you pass down an observed object, properties on that object do remain reactive.

We're passing down only observed objects and methods and methods. `i18n` is a method, and if it was  anything wrong with it the translated data would not work on changing the languate (buttons, placeholder, labels etc)

**Comment by YacoubBelaoura** [comment]
ok thanks, 

but i have the same problem for RTL now. and i wanted to keep the idea of V3 as reusable component outside Enso, the problem i have now is only for Forms and Tables. i used a new approach from the last one, to keep this **great** idea.

* the problem for Forms is the vue-select.
* and for tables is with the top controls `dropdown` .

you will have to refresh or get back and return to get it fixed

![output_bug](https://user-images.githubusercontent.com/18699402/55422770-4ee97200-5574-11e9-8ddd-5a814c3c6fa3.gif)

@aocneanu can you give me an idea or a solution ?

all the other features  works great

![output](https://user-images.githubusercontent.com/18699402/55423067-0e3e2880-5575-11e9-96da-0ddf24badbc5.gif)

**Comment by YacoubBelaoura** [comment]
i think i will just use a `prop` instead on an `inject`. it wont effect *re-usability*.
