### ISSUE TITLE
Could I capture the errors of the form from a custom field?

### ISSUE THREAD

**Issue by heyner29** [enso-ui/forms#8]
This is  a **bug | feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

I have a form with a custom field which I use to send a matrix to the BE, the BE validates it correctly and returns the error to the FE but I can not capture it in the FE.

In the array of errors of the computed form are received well.  could I access that array in any way?  Or is there a better way to capture these errors?

Thank you in advance for all your help!

**Comment by aocneanu** [comment]
`this.$refs.myForm.errors`

**Comment by heyner29** [comment]
Thank you very much, that was the solution I was looking for!
